### ISSUE TITLE
Remote I/O error

### ISSUE THREAD

**Issue by ParcoMolo** [DFRobot/DFRobot_STS3X#1]
Hey guys,

I've been trying to get this sensor working on a pi but for some reason I keep getting this remote I/O error.

Hardware:
- RPI 3B V1.2
- STS35

Wiring:
- STS35 VCC - RPI 5V pinout (tested the voltage - 4.01V)
- STS35 GND - RPI GND pinout
- STS SDA - RPI SDA pinout
- STS SCL - RPI SCL pinout

Log printout:

`Traceback (most recent call last):
  File "get_temperature_period.py", line 45, in <module>
    setup()
  File "get_temperature_period.py", line 26, in setup
    sensor.begin()
  File "/home/pi/DFRobot_STS3X/python/raspberrypi/DFRobot_STS3X.py", line 157, in begin
    self.sensor_reset()
  File "/home/pi/DFRobot_STS3X/python/raspberrypi/DFRobot_STS3X.py", line 264, in sensor_reset
    self.sensor_break()
  File "/home/pi/DFRobot_STS3X/python/raspberrypi/DFRobot_STS3X.py", line 258, in sensor_break
    self._write_command(STS3X_CMD_MEA_PER_BREAK_MSB, [STS3X_CMD_MEA_PER_BREAK_LSB])
  File "/home/pi/DFRobot_STS3X/python/raspberrypi/DFRobot_STS3X.py", line 410, in _write_command
    self._i2c.write_i2c_block_data(self._i2c_addr, cmd_msb, cmd_lsb)
IOError: [Errno 121] Remote I/O error
`

i2cdetect -y 1 printout:

![image](https://user-images.githubusercontent.com/46521867/186758175-2904bdf6-feca-491b-998f-370ce31d8d0e.png)

I know for a fact that the sensor is working since I tested it on a Arduino Leonardo.

Can someone please point me in a direction?

**Comment by qsjhyy** [comment]
Hey guys,
From the picture, the address you scanned is 0x4b, which is different from the default 0x4a in Demo. Have you tried to change the address of module i2c in Demo:
```python

# Determine I2C address according to the ADDR pin pull-up or pull-down
# ADDR pin pull-down: STS3X_I2C_ADDRESS_A   0x4A
# ADDR pin pull-up: STS3X_I2C_ADDRESS_B   0x4B
sensor = DFRobot_STS3X(i2c_addr = STS3X_I2C_ADDRESS_A,bus = 1)

```

**Comment by ParcoMolo** [comment]
I feel like such a idiot... you are correct. 

From reading the specs on your site I took that 0x4B would be used by default 
![image](https://user-images.githubusercontent.com/46521867/186904358-87a89913-3ca4-4151-ae39-04e3503a7bab.png)

but I should've just used my eyes xD

Thanks @qsjhyy

**Comment by qsjhyy** [comment]
It was really an oversight on my part. I think I subconsciously took the letter A as the default. I've changed the default address used for the Python examples for now, because it's really misleading.
Thanks @ParcoMolo
